language: python

python:
  - "3.6"

branches:
  only:
    - master

install:
    - pip install .
    - pip install coveralls

script:
  - python -bb -m coverage run -p --source=pimpmyclass --omit="*test*" setup.py test
  - coverage combine
  - coverage report -m

after_success:
  - coveralls --verbose
